openapi:  3.0.0
info:
  title: Social App
  description: Our First Social App 
  version: 1.0.1

servers: 
  # - url: http://localhost:4000
  #   description: home page of our app
  - url: http://localhost:4000/api/v1
    description: instagram page of our app

# components:
#   securitySchemes:
#     BasicAuth:
#       type: http
#       scheme: basic
#     BearerAuth:
#       type: http
#       scheme: bearer    


paths:  
  /linkedin:
    get:
      summary: returns username, followers and follows
      responses:
       '200':  # status code
         description : return an object
         content: 
          application/json:
            schema: 
              type: object
              properties: 
                username:
                    type: string 
                followers:
                    type: string
                follows: 
                    type: string  
    post:
      summary: returns username, followers and follows
      responses:
       '200':  # status code
         description : return an object
         content: 
          application/json:
            schema: 
              type: object
              properties: 
                username:
                    type: string 
                followers:
                    type: string
                follows: 
                    type: string    

  /{token}: 
    get: 
        summary: returns username, followers and follows
        parameters: 
          - name: token
            default : 5
            in: path
        responses:
        '200':  # status code
          description : return an object
          content: 
            application/json:
             
                



     